---
- name: ensure "Docker repository GPG key" is present
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: ensure "Docker repository" is present
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker-ce

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"

- name: ensure "docker.io" is purged
  apt:
    name: docker.io
    state: absent
    purge: yes
  when: ansible_distribution == 'Ubuntu'

- name: ensure "docker" is purged
  apt:
    name: docker
    state: absent
    purge: yes
  when: ansible_distribution == 'Debian'

- name: ensure "docker-ce" is present
  apt:
    name: docker-ce
    state: present

